'''DESAFIOS

DESAFIO 1:
VOCÊ QUER SIMULAR A OPÇÃO DE JOGAR UMA MOEDA E RESULTAR EM CARA OU COROA. JOGUE AS OPÕES DENTRO DE UMA LISTA E DEPOIS
 CRIE UM PROGRAMA QUE IMPRIMA 'CARA' OU 'COROA' NA TELA.'''
import random

moeda = ['cara', 'coroa']
print(random.choice(moeda))

'''DESAFIO 2
 VOCÊ QUER FAZER UM SORTEIO ENTRE 5 NOMES EM UMA LISTA DE NOMES. CRIE UMA LISTA DE 5 NOMES E SORTEI UM NOME DENTRO 
 DESSA LISTA E EXIBA NA TELA'''
nomes = ['Maurício', 'Daiana', 'Pedro', 'Aline', 'Ana']
print(random.choice(nomes))
'''DESAFIO 3
 VOCÊ QUER ESCOLHER ALEATÓRIAMENTE UM NÚMERO DE 10-100. IMPRIMA NA TELA UM VALOR ALEATÓRIO ENTRE 10 E 100.'''
print(random.randint(10, 100))
